Point cloud shader
CMP2804/Assessment2 pull request #20
Opened 2023-03-03 19:09 UTC by Vesper-Works

2023-03-05 22:31 UTC, StevieGoodman requested changes
Okay, there's nothing game-breaking here, but I've given a few tips that I would recommend acting upon, but don't feel compelled to

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudObject.cs
> +            foreach (Mesh mesh in _meshes)
This `foreach` loop doesn't need braces - it has only 1 line

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudObject.cs
> +            //computeShader.SetBuffer(0, "_Points", pointBuffer);
This comment should be removed.

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudObject.cs
> +            //computeShader.SetBuffer(0, "_Points", pointBuffer);
This comment should be removed.

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudObject.cs
> +            foreach (Mesh mesh in _meshes)
This `foreach` loop doesn't need braces - it has only 1 line

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudObject.cs
> +            if (parent.TryGetComponent(out MeshFilter meshFilter))
Remove braces

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudObject.cs
> +            //material.SetFloat("_ColorFromTextureLerp", colorFromTextureLerp);
These comments should be removed

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudObject.cs
> +                Matrix4x4.TRS(new Vector3(0, 0, 0), transform.rotation, new Vector3(1, 1, 1)));
Inconsistent indentation. To provide context, I would extract variables for the first and last arguments in `Matrix4x4.RTS()`, as well as the function return itself.

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudObject.cs
> +        [SerializeField] private ComputeShader computeShader;
For consistency (and functionality), replace all `[SerializeField]` with `[OdinSerialize]` as this supports more advanced types

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudObject.cs
> +    public class PointCloudObject : MonoBehaviour
Derive from `SerializedMonoBehaviour` instead for access to property serialization

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudRenderer.cs
> +            // for (int i = 0; i < _lifespans.Count; i++)
Pleass remove comments

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/PointCloudRenderer.cs
> +                if (_lifespans[i] <= 0)
I would recommend extracting the contents of this `if` statement and replacing it with `if (_lifespans[i] <= 0) functionName();`

2023-03-05 22:31 UTC, StevieGoodman commented on Assets/Scripts/Point Cloud/SoundMaker.cs
> +        [Header("Emission settings")] [SerializeField]
Recommend replacing this with `[Title(title, description)` as this is Odin's implementation

2023-03-08 10:38 UTC, StevieGoodman requested changes
Please resolve merge conflicts

2023-03-08 18:56 UTC, Vesper-Works commented
Ready

2023-03-17 12:48 UTC, StevieGoodman approved these changes
https://media.istockphoto.com/id/513921039/photo/illustration-of-a-oool-yellow-smiley-with-sunglasses.jpg?s=612x612&w=0&k=20&c=hhVQxXTUhmcZLv2QrZ2WE2p7inzxQIA5H6XP8jPrQXw=

2023-03-17 12:48 UTC, merged